#### general settings
name: ClassSR_RCAN
use_tb_logger: true
model: ClassSR
distortion: sr
scale: 4
gpu_ids: [0,1,4]
patch_size: 32
step: 28
fix_SR_module: true



#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT_rcan
    dataroot_GT: /data0/xtkong/data/DIV2K_scale_sub/GT
    dataroot_LQ: /data0/xtkong/data/DIV2K_scale_sub/LR

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 60
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2K10
    mode: LQGT_rcan
    dataroot_GT: /data0/xtkong/ClassSR_hengyuan2/datasets/val_10/HR/X4
    dataroot_LQ: /data0/xtkong/ClassSR_hengyuan2/datasets/val_10/LR/X4

#### network structures
network_G:
  which_model_G: classSR_3class_rcan
  in_nc: 3
  out_nc: 3

#### path
path:
  pretrain_model_G: ~
  pretrain_model_classifier: ~
  pretrain_model_G_branch1: /data0/xtkong/ClassSR-github/experiments/pre_trained_models/RCAN_branch1.pth
  pretrain_model_G_branch2: /data0/xtkong/ClassSR-github/experiments/pre_trained_models/RCAN_branch2.pth
  pretrain_model_G_branch3: /data0/xtkong/ClassSR-github/experiments/pre_trained_models/RCAN_branch3.pth
  resume_state: ~
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 3e-5
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 200000
  warmup_iter: -1  # no warm up
  T_period: [500000, 20000]
  restarts: [500000]
  restart_weights: [0.5]
  eta_min: !!float 2e-6

  pixel_criterion: ClassSR_loss
  l1w: 4
  class_loss_w: 0.5
  average_loss_w: 3

  manual_seed: 10
  val_freq: !!float 1000

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2000
